
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 03 20:29:12 CET 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 21;
  public static final int LLCIERRE = 20;
  public static final int POR = 9;
  public static final int CCIERRE = 35;
  public static final int GE = 13;
  public static final int CIRCUNFLEJO = 37;
  public static final int PCIERRE = 4;
  public static final int LITERALREAL = 24;
  public static final int CAP = 34;
  public static final int WRITE = 50;
  public static final int DELETE = 48;
  public static final int E = 22;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int LT = 14;
  public static final int TYPE = 52;
  public static final int LLAP = 19;
  public static final int EVAL = 11;
  public static final int OR = 28;
  public static final int BOOL = 30;
  public static final int CALL = 53;
  public static final int LITERALCADENA = 39;
  public static final int DIV = 10;
  public static final int IF = 43;
  public static final int LE = 15;
  public static final int EOF = 0;
  public static final int AMP = 38;
  public static final int ASIG = 5;
  public static final int TRUE = 25;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int COMA = 6;
  public static final int MENOS = 8;
  public static final int NULL = 41;
  public static final int MOD = 33;
  public static final int EQ = 16;
  public static final int REAL = 32;
  public static final int ENT = 31;
  public static final int PAP = 3;
  public static final int ELSE = 44;
  public static final int PUNTO = 36;
  public static final int NL = 51;
  public static final int READ = 49;
  public static final int IDEN = 2;
  public static final int WHILE = 45;
  public static final int NE = 17;
  public static final int PROC = 42;
  public static final int STRING = 40;
  public static final int FALSE = 26;
  public static final int STRUCT = 46;
  public static final int GT = 12;
  public static final int PYC = 18;
  public static final int LITERALENTERO = 23;
  public static final int MAS = 7;
}

