
public enum ClaseLexica {
	IDEN, PAP, PCIERRE, ASIG,  
	MAS, MENOS, POR, DIV, EVAL, EOF, 
	
	GT, GE, LT, LE, EQ, NE, PYC, LLAP, LLCIERRE, SEP, E,LITERALENTERO, LITERALREAL,
	
	TRUE, FALSE, AND, OR, NOT, BOOL,ENT, REAL
}
