
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Tue May 07 19:00:09 CEST 2024
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 9;
  public static final int LLCIERRE = 8;
  public static final int POR = 33;
  public static final int GE = 36;
  public static final int CCIERRE = 13;
  public static final int CIRCUNFLEJO = 45;
  public static final int PCIERRE = 3;
  public static final int LITERALREAL = 47;
  public static final int CAP = 52;
  public static final int DELETE = 23;
  public static final int WRITE = 25;
  public static final int NOT = 44;
  public static final int AND = 42;
  public static final int LT = 37;
  public static final int LLAP = 7;
  public static final int TYPE = 27;
  public static final int OR = 43;
  public static final int EVAL = 5;
  public static final int BOOL = 10;
  public static final int CALL = 28;
  public static final int LITERALCADENA = 48;
  public static final int DIV = 34;
  public static final int IF = 18;
  public static final int LE = 38;
  public static final int EOF = 0;
  public static final int ASIG = 30;
  public static final int AMP = 15;
  public static final int TRUE = 49;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int COMA = 4;
  public static final int MENOS = 32;
  public static final int NULL = 51;
  public static final int MOD = 41;
  public static final int EQ = 39;
  public static final int REAL = 12;
  public static final int ENT = 11;
  public static final int PAP = 2;
  public static final int ELSE = 19;
  public static final int PUNTO = 14;
  public static final int NL = 26;
  public static final int READ = 24;
  public static final int IDEN = 29;
  public static final int WHILE = 20;
  public static final int NE = 40;
  public static final int PROC = 17;
  public static final int STRING = 16;
  public static final int FALSE = 50;
  public static final int STRUCT = 21;
  public static final int GT = 35;
  public static final int LITERALENTERO = 46;
  public static final int PYC = 6;
  public static final int MAS = 31;
}

